server:
  port: 8085

spring:
  application:
    name: PAYMENT-SERVICE

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/railbook_payment}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root@123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.railbook.paymentservice.event.BookingCreatedEvent
        spring.json.trusted.packages: com.railbook.paymentservice.event
        spring.json.use.type.headers: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

  instance:
    prefer-ip-address: true

payment:
  simulation:
    result: ${PAYMENT_SIMULATION_RESULT:SUCCESS}