spring:
  application:
    name: booking-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/railbook_booking}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root@123}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          # Must match the "iss" claim inside the JWT
          issuer-uri: ${KEYCLOAK_ISSUER:http://localhost:8080/realms/RailBook}

          # Allows Dockerized Booking Service to reach Keycloak
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/RailBook/protocol/openid-connect/certs}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: booking-event-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.railbook.bookingservice.event


server:
  port: 8083


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

  health:
    circuit-breakers:
      enabled: true


services:
  train-service:
    url: ${TRAIN_SERVICE_URL:http://localhost:8082}

  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8081}


resilience4j:
  circuitbreaker:
    instances:

      user-service:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException.NotFound

      train-service:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException.NotFound

    circuit-breaker-aspect-order: 1


  retry:
    instances:

      user-service:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.RestClientException
          - java.io.IOException
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException.NotFound

      train-service:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.RestClientException
          - java.io.IOException
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException.NotFound

    retry-aspect-order: 2


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

  instance:
    prefer-ip-address: true